laser models update

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -1,8 +1,8 @@
 #!/bin/bash
-cd "${0%/*}" || exit  # Run from this directory
+cd "${0%/*}" || exit 1
 
-# Stop at first error
 set -e
+set -o pipefail
 
 # Check if OpenFOAM/FOAM has been sourced
 if [[ -z "${WM_PROJECT}" ]]
@@ -11,7 +11,9 @@ then
     exit 1
 else
     allowed_ver=("v2412" "v2506")
-    if ! [[ " ${allowed_ver[*]} " == *" $WM_PROJECT_VERSION "* ]]; then
+
+    if ! [[ " ${allowed_ver[*]} " == *" $WM_PROJECT_VERSION "* ]]
+    then
         echo "Unsupported OpenFOAM version sourced!"
     fi
 fi
@@ -22,24 +24,27 @@ then
     . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments
 fi
 
-# Compile applications
-(cd applications && ./Allwmake $* 2>&1 | tee log.Allwmake)
+(
+    cd applications
+    ./Allwmake "$@" 2>&1 | tee log.Allwmake
+)
 
 # Check if the build succeeded
 echo "Checking if the installation was a success:"
-N_ERRORS_1=$(find . -name log.Allwmake | xargs grep " Error " | wc -l)
-N_ERRORS_2=$(find . -name log.Allwmake | xargs grep " Stop." | wc -l)
+N_ERRORS_1=$({ find . -name log.Allwmake -exec grep -h " Error " {} + || true; } | wc -l)
+N_ERRORS_2=$({ find . -name log.Allwmake -exec grep -h " Stop." {} + || true; } | wc -l)
+
 if [[ $N_ERRORS_1 -gt 0 ]] || [[ $N_ERRORS_2 -gt 0 ]]
 then
     echo "** BUILD ERROR **"
     echo "There were build errors in the following logs:"
-    echo $(find . -name log.Allwmake | xargs grep -l " Error ")
-    echo $(find . -name log.Allwmake | xargs grep -l " Stop.")
+    find . -name log.Allwmake -exec grep -l " Error " {} +
+    find . -name log.Allwmake -exec grep -l " Stop." {} +
     echo; echo "Please examine these logs for additional details"; echo
     exit 1
 else
     echo
-    echo "There were no build errors: enjoy laserbeamFoam!"; echo
+    echo "There were no build errors: enjoy laserHeatFoam!"; echo
 fi
 echo
 
